Bugfix/view corrections
JakubBilski/tonations-recognition pull request #62
Opened 2021-01-04 23:45 UTC by AnnaMBuchman

1. move record section to top
2. change proportions of record img
3. add file section with check icon
4. update menu
5. decrease section paddings 
6. move narrow down button to record section, after click it moves to music options
![obraz](https://user-images.githubusercontent.com/34186018/103591030-47948c80-4eef-11eb-9cba-582dc1788731.png)

2021-01-05 18:30 UTC, JakubBilski requested changes
I don't like the green check thing, I feel it would be more clear without it.
Also, the layout of the whole page feels centered. How about centering this, too?
![image](https://user-images.githubusercontent.com/47048420/103683972-2da88780-4f8b-11eb-9750-d171043b3aa3.png)
(I also changed the font weights to make "Uploaded file" similar to "Get file" from the recording section)
Instead of writing "Uploaded file: no file selected!", I would say it's better to put "No file selected". It's closer to natural language and feel more elegant.
![image](https://user-images.githubusercontent.com/47048420/103684629-2afa6200-4f8c-11eb-80aa-3ebb0c5c99d5.png)

2021-01-05 18:33 UTC, JakubBilski commented on view-app/src/css/templatemo-breezed.css
> +/*file_cestion*/
/*file_section*/

2021-01-05 18:37 UTC, JakubBilski commented on view-app/src/css/templatemo-breezed.css
> +/*choose_cestion*/
section

2021-01-06 14:56 UTC, AnnaMBuchman commented
I think it looks better now ;)

2021-01-06 15:35 UTC, JakubBilski commented
Now = on my screens? Should I apply my changes here?

2021-01-06 15:41 UTC, JakubBilski commented
@JakubBrojacz what do you think?

2021-01-06 15:49 UTC, JakubBrojacz commented
The only thing I would change is that for someone who opens our app for the first time text "No file selected" is strange. I thing it would be better to just show "about us"

2021-01-06 15:52 UTC, JakubBrojacz commented
We could also remove 
![obraz](https://user-images.githubusercontent.com/38508437/103788739-7ae63100-503f-11eb-9f44-339b0d82f94a.png)
this thing

2021-01-06 15:53 UTC, JakubBilski commented
Ok, I agree

2021-01-06 15:54 UTC, JakubBilski approved these changes

2021-01-06 22:47 UTC, merged